### PR TITLE
Use clang's built-in header search paths

### PR DESCRIPTION
**Pull request by spaceotter**
I think I found the right incantation for this in an example. For me this works without manually specifying the header paths.

### CODE REVIEW

**Comment by rpav** [comment]
Wait so does this actually pull in the right headers for system stuff?  We can probably dump the crappy "wild guess" stuff if this is accurate.

**Comment by rpav** [comment]
This is *great* and it's a huge step toward fixing a longstanding issue, but I think there's something left to configure ... this finds all the system headers (awesome!) but seems to error on some intrinsics, e.g. if I `c2ffi /usr/include/SDL2/SDL.h`, I get errors about `/usr/lib/clang/11.1.0/include/xmmintrin.h:52:6`.

Since you're in the depths of the docs to find this, you may find this faster than I .. maybe target triple is getting reset (wild guess) or something related to intrinsics-available.  Otherwise I'll take a look at this but my time is a bit limited at the moment.

I think if this gets fixed though you can just remove the old hack and default to this.

**Comment by rpav** [comment]
Err, this is what I get for trying to merge on less than a cup of coffee.

This actually *doesn't* seem to fully find headers, e.g., it can't find `<sys/types.h>` ... the intrinsics issue is separate (but doesn't seem to be the result of a header .. maybe 11.1 or prior and I didn't notice).

If you can use SDL2 or some similar "real" library that pulls a lot of system stuff, it should be a good indication of whether configuration is correct.  I'll have a look around this API though.

**Comment by spaceotter** [comment]
Looks like my testing was somewhat lacking. I can try it with SDL later.
Note that I found this by browsing the clang source code and running it in GDB. The documentation isn't very helpful from what I've seen.

**Comment by rpav** [comment]
Yeah sadly the internal API docs are mostly "this function seems to have an interesting name," and "let's look at the source to see what it does."

The above looks like it assumes the current binary is in the vicinity of a full clang installation, which may not be the case .. e.g., c2ffi may not be installed (run from build dir), and clang may be system-installed but c2ffi may be in `/usr/local` etc.  This may be on the right track though.

**Comment by spaceotter** [comment]
This is able to find stdint.h in my test where before it couldn't. Still need to try something more substantial.
This brings in the whole clang argument parser, which is maybe not great. It might make sense to allow arbitrary options to be forwarded to clang's argument parser, but I've avoided changing the c2ffi interface.

**Comment by spaceotter** [comment]
It doesn't work with SDL. I'm looking into it.

**Comment by spaceotter** [comment]
I'm now getting a lot of use of `undeclared identifier '__builtin_labs'` type errors in c++. This happens even if you specify the headers manually with current llvm-11.0.0 branch. The output might be usable.

With this:
```
echo '#include <SDL2/SDL.h>' > test.h
build/bin/c2ffi -x c -D json test.h -o test.spec
```
I also get a ton of errors. But the SDL api functions appear in the json. So it's "fixed" ... I guess?

I should note that I've been cribbing https://github.com/MaskRay/ccls

**Comment by spaceotter** [comment]
The nostdinc option is probably broken. I'll check it tomorrow.

**Comment by spaceotter** [comment]
That should clear up the issues I know about, let me know if this works for you @rpav.

**Comment by kojix2** [comment]
This pull request is useful. Thank you.

**Comment by rpav** [comment]
Thanks!  This definitely seems to parse things correctly here.  I think the intrinsics issue is another platform-related setting that probably needs set, and is unrelated to this patch.  (An 11.1.0 perhaps, but I might have overlooked it for awhile since it produces output.)

**Comment by spaceotter** [comment]
Actually, the issue I mentioned should have been fixed by 44ea9c9 in this PR.

**Comment by attila-lendvai** [comment]
i'm trying to regenerate the specs of `hu.dwim.sdl` using this invocation of the latest 11.0.0 branch:

```
c2ffi hu.dwim.sdl/c2ffi-spec/sdl.h --driver null --macro-file /tmp/tmp65D7UMZD.tmp --arch x86_64-pc-linux-gnu --sys-include /nix/store/w1aqvvk0c0q87nj8x9kgs5ix9ka6z3qq-SDL2-2.0.12-dev/include
```

and `sys/types.h` is not found:

```
In file included from /home/alendvai/common-lisp/hu.dwim.sdl/c2ffi-spec/sdl.h:1:
In file included from /nix/store/w1aqvvk0c0q87nj8x9kgs5ix9ka6z3qq-SDL2-2.0.12-dev/include/SDL2/SDL.h:32:
In file included from /nix/store/w1aqvvk0c0q87nj8x9kgs5ix9ka6z3qq-SDL2-2.0.12-dev/include/SDL2/SDL_main.h:25:
/nix/store/w1aqvvk0c0q87nj8x9kgs5ix9ka6z3qq-SDL2-2.0.12-dev/include/SDL2/SDL_stdinc.h:34:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
Skipping invalid Decl:
TypedefDecl 0x1fdf9b8 </nix/store/w1aqvvk0c0q87nj8x9kgs5ix9ka6z3qq-SDL2-2.0.12-dev/include/SDL2/SDL_stdinc.h:173:1, col:16> col:16 invalid Sint8 'int'
`-BuiltinType 0x1fce870 'int'
[...]
```

keep in mind that nix/nixos is a strange setup, so this could very well be a nixos related issue, but maybe it rings a bell?

**Comment by spaceotter** [comment]
Check that the location of sys/types.h (`locate sys/types.h`) is in the search path from `clang -E -x c - -v < /dev/null`.

**Comment by attila-lendvai** [comment]
@spaceotter  thanks!

```
$ clang -E -x c - -v < /dev/null
clang version 11.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/bin
Found candidate GCC installation: /nix/store/fvf3qjqa5qpcjjkq37pb6ypnk1mzhf5h-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0
Found candidate GCC installation: /nix/store/fvf3qjqa5qpcjjkq37pb6ypnk1mzhf5h-gcc-9.3.0/lib64/gcc/x86_64-unknown-linux-gnu/9.3.0
Selected GCC installation: /nix/store/fvf3qjqa5qpcjjkq37pb6ypnk1mzhf5h-gcc-9.3.0/lib64/gcc/x86_64-unknown-linux-gnu/9.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 (in-process)
 "/nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/bin/clang-11" -cc1 -triple x86_64-unknown-linux-gnu -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -fno-split-dwarf-inlining -debugger-tuning=gdb -v -nostdsysteminc -resource-dir /nix/store/vpv81n0378fgks53074f6sqi9h9qwvkg-clang-wrapper-11.0.0/resource-root -idirafter /nix/store/ch44wa8qqss0dm04lnvf5n7mfh23kmrv-glibc-2.31-74-dev/include -isystem /nix/store/sy8c25yavz1p7n1bfkp17wp45ahwcr6r-gdb-9.2/include -isystem /nix/store/a9g7p6fwanw66j5djzila7ql1hky759z-bash-interactive-4.4-p23-dev/include -isystem /nix/store/w9n2h1df4r9151hhjj2h9d2glc06p5d5-llvm-11.0.0/include -isystem /nix/store/d6mn5xdxx1wf1hdzsv5w7w2bk7w33hj5-ncurses-6.2-dev/include -isystem /nix/store/0lw9cy84523dp7ljw6l6g818w5pdixlc-zlib-1.2.11-dev/include -isystem /nix/store/y927pv087xygs1g3xh98zliqwnm7l1df-compiler-rt-11.0.0-dev/include -internal-isystem /nix/store/vpv81n0378fgks53074f6sqi9h9qwvkg-clang-wrapper-11.0.0/resource-root/include -fdebug-compilation-dir /home/alendvai/workspace/c2ffi -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -faddrsig -o - -x c -
clang -cc1 version 11.0.0 based upon LLVM 11.0.0 default target x86_64-unknown-linux-gnu
#include "..." search starts here:
#include <...> search starts here:
 /nix/store/sy8c25yavz1p7n1bfkp17wp45ahwcr6r-gdb-9.2/include
 /nix/store/a9g7p6fwanw66j5djzila7ql1hky759z-bash-interactive-4.4-p23-dev/include
 /nix/store/w9n2h1df4r9151hhjj2h9d2glc06p5d5-llvm-11.0.0/include
 /nix/store/d6mn5xdxx1wf1hdzsv5w7w2bk7w33hj5-ncurses-6.2-dev/include
 /nix/store/0lw9cy84523dp7ljw6l6g818w5pdixlc-zlib-1.2.11-dev/include
 /nix/store/y927pv087xygs1g3xh98zliqwnm7l1df-compiler-rt-11.0.0-dev/include
 /nix/store/vpv81n0378fgks53074f6sqi9h9qwvkg-clang-wrapper-11.0.0/resource-root/include
 /nix/store/ch44wa8qqss0dm04lnvf5n7mfh23kmrv-glibc-2.31-74-dev/include
End of search list.
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 341 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
```

if i add `/nix/store/ch44wa8qqss0dm04lnvf5n7mfh23kmrv-glibc-2.31-74-dev/include` to the includes (see the c2ffi invocation below), then sys/types.h is found, but i get loads of errors like this:

```
; Invoking: /home/alendvai/workspace/c2ffi/build/bin/c2ffi /home/alendvai/common-lisp/hu.dwim.sdl/c2ffi-spec/sdl.h --driver null --macro-file /tmp/tmp65D7UMZD.tmp --arch x86_64-pc-linux-gnu --sys-include /nix/store/w1aqvvk0c0q87nj8x9kgs5ix9ka6z3qq-SDL2-2.0.12-dev/include --sys-include /nix/store/ch44wa8qqss0dm04lnvf5n7mfh23kmrv-glibc-2.31-74-dev/include
In file included from /home/alendvai/common-lisp/hu.dwim.sdl/c2ffi-spec/sdl.h:1:
In file included from /nix/store/w1aqvvk0c0q87nj8x9kgs5ix9ka6z3qq-SDL2-2.0.12-dev/include/SDL2/SDL.h:38:
In file included from /nix/store/w1aqvvk0c0q87nj8x9kgs5ix9ka6z3qq-SDL2-2.0.12-dev/include/SDL2/SDL_cpuinfo.h:86:
In file included from /nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/lib/clang/11.0.0/include/immintrin.h:15:
/nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/lib/clang/11.0.0/include/mmintrin.h:67:40: error: passing '__v2si' (aka 'int') to parameter of incompatible type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values)
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
                                       ^~~~~~~~~~~
/nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/lib/clang/11.0.0/include/mmintrin.h:129:43: error: passing '__v4hi' (aka 'short') to parameter of incompatible type '__attribute__((__vector_size__(4 * sizeof(short)))) short' (vector of 4 'short' values)
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
                                          ^~~~~~~~~~~~
...
```

any ideas/hints are appreciated.

**Comment by spaceotter** [comment]
I remember getting errors like that at some intermediate stage of developing this, but unfortunately not what fixed it.
If clang lists that directory as above, it should be included already, unless you are building against a libclang that is separate from the clang executable?
Perhaps the CLANG_RESOURCE_DIR is not being set correctly? What is `clang -print-resource-dir`?

**Comment by attila-lendvai** [comment]
```
$ clang -print-resource-dir
/nix/store/vpv81n0378fgks53074f6sqi9h9qwvkg-clang-wrapper-11.0.0/resource-root
```

could be that nixos complicates the situation. i build the `c2ffi` executable in a local environment, but that output above is the same in both envs, and both env should have the same `clang_11` nix package.

> unless you are building against a libclang that is separate from the clang executable?

unfortunately i don't know how to answer this question.

> If clang lists that directory as above, it should be included already

yet, i think that is not the case in my env, because without adding it as a `--sys-include` to the `c2ffi` call, `sys/types.h` is not found.

i'll play more with this later, as time allows.

**Comment by spaceotter** [comment]
TBH i had never heard of nixos, it looks kinda weird so I'm not surprised you're having issues.
If you use this patch and the -v option it adds, it dumps the internal arguments that clang is using. You can compare with the arguments printed by the previous `clang -E -x c - -v < /dev/null` command.
https://github.com/spaceotter/c2ffi/commit/e484be30dec54bf367ce36dca88cdf1f794c578a

**Comment by spaceotter** [comment]
For example, here's a result in Manjaro Linux:
<details>

```
clang internal args:
arg 0: -cc1
arg 1: -triple
arg 2: x86_64-pc-linux-gnu
arg 3: -fsyntax-only
arg 4: -disable-free
arg 5: -disable-llvm-verifier
arg 6: -discard-value-names
arg 7: -main-file-name
arg 8: test.h
arg 9: -mrelocation-model
arg 10: pic
arg 11: -pic-level
arg 12: 2
arg 13: -pic-is-pie
arg 14: -mframe-pointer=all
arg 15: -fmath-errno
arg 16: -fno-rounding-math
arg 17: -mconstructor-aliases
arg 18: -munwind-tables
arg 19: -target-cpu
arg 20: x86-64
arg 21: -fno-split-dwarf-inlining
arg 22: -debugger-tuning=gdb
arg 23: -resource-dir
arg 24: /usr/lib/clang/11.1.0
arg 25: -internal-isystem
arg 26: /usr/local/include
arg 27: -internal-isystem
arg 28: /usr/lib/clang/11.1.0/include
arg 29: -internal-externc-isystem
arg 30: /include
arg 31: -internal-externc-isystem
arg 32: /usr/include
arg 33: -fdebug-compilation-dir
arg 34: /home/eric/src/c2ffi
arg 35: -ferror-limit
arg 36: 19
arg 37: -stack-protector
arg 38: 2
arg 39: -fgnuc-version=4.2.1
arg 40: -faddrsig
arg 41: -x
arg 42: c-header
arg 43: test.h
```

</details>

**Comment by attila-lendvai** [comment]
@spaceotter unfortunately my C foo is rusty, but it looks to me that for some reason `c2ffi` doesn't include the `glibc` headers on nixos.

the reason is probably the `-nostdsysteminc` in the args. where is it coming from? any ideas how i can get rid of it?

a hint about nixos that may be relevant here: it configures/compiles every package so that there are full-path references to the actual binary files in the `/nix/store` directory, and similarly deals with include paths, and in general with compile time dependencies. there is a thing called a wrapper. these are scripts that set up the right env variables before running the executables. clang also has such a wrapper script. maybe clang is compiled in such a way on nixos that `-nostdsysteminc` is included by default, and the wrapper script specifies the right version externally and explicitly?

if i provide the missing glibc include path as a `--sys-include` to the `c2ffi` run, then i get the intrinsics related type mismatch error. (maybe an ordering issue among the sysincludes?)

any hints are appreciated, and thank you for your efforts!

```
$ nix-shell -p llvmPackages_11.clang

[nix-shell:~]$ clang -E -x c - -v < /dev/null
clang version 11.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/bin
Found candidate GCC installation: /nix/store/fvf3qjqa5qpcjjkq37pb6ypnk1mzhf5h-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0
Found candidate GCC installation: /nix/store/fvf3qjqa5qpcjjkq37pb6ypnk1mzhf5h-gcc-9.3.0/lib64/gcc/x86_64-unknown-linux-gnu/9.3.0
Selected GCC installation: /nix/store/fvf3qjqa5qpcjjkq37pb6ypnk1mzhf5h-gcc-9.3.0/lib64/gcc/x86_64-unknown-linux-gnu/9.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 (in-process)
 "/nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/bin/clang-11" -cc1
 -triple x86_64-unknown-linux-gnu -E -disable-free -disable-llvm-verifier
 -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2
 -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases
 -munwind-tables -target-cpu x86-64 -fno-split-dwarf-inlining -debugger-tuning=gdb
 -v -nostdsysteminc -resource-dir /nix/store/vpv81n0378fgks53074f6sqi9h9qwvkg-clang-wrapper-11.0.0/resource-root
 -idirafter /nix/store/ch44wa8qqss0dm04lnvf5n7mfh23kmrv-glibc-2.31-74-dev/include
 -isystem /nix/store/y927pv087xygs1g3xh98zliqwnm7l1df-compiler-rt-11.0.0-dev/include
 -isystem /nix/store/y927pv087xygs1g3xh98zliqwnm7l1df-compiler-rt-11.0.0-dev/include
 -isystem /nix/store/y927pv087xygs1g3xh98zliqwnm7l1df-compiler-rt-11.0.0-dev/include
 -D _FORTIFY_SOURCE=2 -internal-isystem /nix/store/vpv81n0378fgks53074f6sqi9h9qwvkg-clang-wrapper-11.0.0/resource-root/include
 -O2 -Wformat -Wformat-security -Werror=format-security
 -fdebug-compilation-dir /home/alendvai -ferror-limit 19 -fwrapv -stack-protector 2
 -stack-protector-buffer-size 4 -fgnuc-version=4.2.1 -fcolor-diagnostics
 -vectorize-loops -vectorize-slp -faddrsig -o - -x c -
clang -cc1 version 11.0.0 based upon LLVM 11.0.0 default target x86_64-unknown-linux-gnu
ignoring duplicate directory "/nix/store/y927pv087xygs1g3xh98zliqwnm7l1df-compiler-rt-11.0.0-dev/include"
ignoring duplicate directory "/nix/store/y927pv087xygs1g3xh98zliqwnm7l1df-compiler-rt-11.0.0-dev/include"
#include "..." search starts here:
#include <...> search starts here:
 /nix/store/y927pv087xygs1g3xh98zliqwnm7l1df-compiler-rt-11.0.0-dev/include
 /nix/store/vpv81n0378fgks53074f6sqi9h9qwvkg-clang-wrapper-11.0.0/resource-root/include
 /nix/store/ch44wa8qqss0dm04lnvf5n7mfh23kmrv-glibc-2.31-74-dev/include
End of search list.
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 344 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
```

and a run with your `-v` debug:

```
; Invoking: /home/alendvai/workspace/c2ffi/build/bin/c2ffi
; /home/alendvai/common-lisp/hu.dwim.sdl/c2ffi-spec/sdl.h --driver null
; --macro-file /tmp/tmp8QS36HP2.tmp --arch x86_64-pc-linux-gnu -v
; --sys-include /nix/store/w1aqvvk0c0q87nj8x9kgs5ix9ka6z3qq-SDL2-2.0.12-dev/include
clang internal args:
arg 0: -cc1
arg 1: -triple
arg 2: x86_64-pc-linux-gnu
arg 3: -fsyntax-only
arg 4: -disable-free
arg 5: -disable-llvm-verifier
arg 6: -discard-value-names
arg 7: -main-file-name
arg 8: sdl.h
arg 9: -mrelocation-model
arg 10: static
arg 11: -mframe-pointer=all
arg 12: -fmath-errno
arg 13: -fno-rounding-math
arg 14: -mconstructor-aliases
arg 15: -munwind-tables
arg 16: -target-cpu
arg 17: x86-64
arg 18: -fno-split-dwarf-inlining
arg 19: -debugger-tuning=gdb
arg 20: -nostdsysteminc
arg 21: -resource-dir
arg 22: /nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/lib/clang/11.0.0
arg 23: -internal-isystem
arg 24: /nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/lib/clang/11.0.0/include
arg 25: -fdebug-compilation-dir
arg 26: /home/alendvai/common-lisp/sbcl
arg 27: -ferror-limit
arg 28: 19
arg 29: -fgnuc-version=4.2.1
arg 30: -faddrsig
arg 31: -x
arg 32: c-header
arg 33: /home/alendvai/common-lisp/hu.dwim.sdl/c2ffi-spec/sdl.h
In file included from /home/alendvai/common-lisp/hu.dwim.sdl/c2ffi-spec/sdl.h:1:
In file included from /nix/store/w1aqvvk0c0q87nj8x9kgs5ix9ka6z3qq-SDL2-2.0.12-dev/include/SDL2/SDL.h:32:
In file included from /nix/store/w1aqvvk0c0q87nj8x9kgs5ix9ka6z3qq-SDL2-2.0.12-dev/include/SDL2/SDL_main.h:25:
/nix/store/w1aqvvk0c0q87nj8x9kgs5ix9ka6z3qq-SDL2-2.0.12-dev/include/SDL2/SDL_stdinc.h:34:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
```

**Comment by spaceotter** [comment]
Note that the first output also has `-nostdsysteminc`. You might want to double check that the `clang` command on the PATH is not actually a shell script that invokes clang with extra arguments.

**Comment by attila-lendvai** [comment]
thanks!

hrm, right, `-nostdsysteminc` is present in both.

`clang` is indeed a wrapper script. with enabled debugging, one can observe what it adds to the command line.

this feels like wandering into pure accidental complexity... i'm giving up for now, i need to refill my motivation.

```
$ nix-shell -p llvmPackages_11.stdenv

[nix-shell:~]$ NIX_DEBUG=2 clang -E -x c - -v < /dev/null
HARDENING: disabled flags: pie
HARDENING: Is active (not completely disabled with "all" flag)
HARDENING: enabling fortify
HARDENING: enabling stackprotector
HARDENING: enabling strictoverflow
HARDENING: enabling format
HARDENING: enabling pic
extra flags before to /nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/bin/clang:
  -O2
  -D_FORTIFY_SOURCE=2
  -fstack-protector-strong
  --param
  ssp-buffer-size=4
  -fno-strict-overflow
  -Wformat
  -Wformat-security
  -Werror=format-security
  -fPIC
original flags to /nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/bin/clang:
  -E
  -x
  c
  -
  -v
extra flags after to /nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/bin/clang:
  -target
  x86_64-unknown-linux-gnu
  -B/nix/store/fvf3qjqa5qpcjjkq37pb6ypnk1mzhf5h-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0
  -B/nix/store/476f2aazc10jmxrjv5d5zn536xjab4c0-clang-11.0.0-lib/lib
  -resource-dir=/nix/store/vpv81n0378fgks53074f6sqi9h9qwvkg-clang-wrapper-11.0.0/resource-root
  --gcc-toolchain=/nix/store/fvf3qjqa5qpcjjkq37pb6ypnk1mzhf5h-gcc-9.3.0
  -B/nix/store/0c7c96gikmzv87i7lv3vq5s1cmfjd6zf-glibc-2.31-74/lib/
  -idirafter
  /nix/store/ch44wa8qqss0dm04lnvf5n7mfh23kmrv-glibc-2.31-74-dev/include
  -B/nix/store/vpv81n0378fgks53074f6sqi9h9qwvkg-clang-wrapper-11.0.0/bin/
clang version 11.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/bin
Found candidate GCC installation: /nix/store/fvf3qjqa5qpcjjkq37pb6ypnk1mzhf5h-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0
Found candidate GCC installation: /nix/store/fvf3qjqa5qpcjjkq37pb6ypnk1mzhf5h-gcc-9.3.0/lib64/gcc/x86_64-unknown-linux-gnu/9.3.0
Selected GCC installation: /nix/store/fvf3qjqa5qpcjjkq37pb6ypnk1mzhf5h-gcc-9.3.0/lib64/gcc/x86_64-unknown-linux-gnu/9.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 (in-process)
 "/nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/bin/clang-11" -cc1 -triple x86_64-unknown-linux-gnu -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -fno-split-dwarf-inlining -debugger-tuning=gdb -v -nostdsysteminc -resource-dir /nix/store/vpv81n0378fgks53074f6sqi9h9qwvkg-clang-wrapper-11.0.0/resource-root -idirafter /nix/store/ch44wa8qqss0dm04lnvf5n7mfh23kmrv-glibc-2.31-74-dev/include -D _FORTIFY_SOURCE=2 -internal-isystem /nix/store/vpv81n0378fgks53074f6sqi9h9qwvkg-clang-wrapper-11.0.0/resource-root/include -O2 -Wformat -Wformat-security -Werror=format-security -fdebug-compilation-dir /home/alendvai -ferror-limit 19 -fwrapv -stack-protector 2 -stack-protector-buffer-size 4 -fgnuc-version=4.2.1 -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -o - -x c -
clang -cc1 version 11.0.0 based upon LLVM 11.0.0 default target x86_64-unknown-linux-gnu
#include "..." search starts here:
#include <...> search starts here:
 /nix/store/vpv81n0378fgks53074f6sqi9h9qwvkg-clang-wrapper-11.0.0/resource-root/include
 /nix/store/ch44wa8qqss0dm04lnvf5n7mfh23kmrv-glibc-2.31-74-dev/include
```

and i did some brute force, too, without much luck:

```
$ find /nix/store/ -name *.h -exec grep --with-filename -G "type.*__v2si" {} \;
/nix/store/6g4rv2ph3p6zwaf5h0vy61carzw012vc-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/include/mmintrin.h:typedef int __v2si __attribute__ ((__vector_size__ (8)));
/nix/store/rnwhk3kr3xq9b5cjil58iyd7i6qgam8q-clang-11.1.0/lib/clang/11.1.0/include/mmintrin.h:typedef int __v2si __attribute__((__vector_size__(8)));
/nix/store/6pzqj9q656vc1msa675k75hmhsrfizsy-clang-10.0.1/lib/clang/10.0.1/include/mmintrin.h:typedef int __v2si __attribute__((__vector_size__(8)));
/nix/store/4bvjq5zv54r9h7ddbr0sw4h0ipy1gci7-clang-11.0.0/lib/clang/11.0.0/include/mmintrin.h:typedef int __v2si __attribute__((__vector_size__(8)));
/nix/store/fvf3qjqa5qpcjjkq37pb6ypnk1mzhf5h-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/include/mmintrin.h:typedef int __v2si __attribute__ ((__vector_size__ (8)));
/nix/store/2mgq3kcgv4hmfav47dpgfp2w71dwwqa0-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/include/mmintrin.h:typedef int __v2si __attribute__ ((__vector_size__ (8)));
/nix/store/qp7riqw57hbb44vniphzac7q8frpcnb3-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/include/mmintrin.h:typedef int __v2si __attribute__ ((__vector_size__ (8)));
/nix/store/hq3ps9kak12kw08hgacpjr4y4i9ias2l-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/include/mmintrin.h:typedef int __v2si __attribute__ ((__vector_size__ (8)));
/nix/store/skvmjkl1xqhxy731brf0bmn7qvbwdqq0-clang-11.0.0/lib/clang/11.0.0/include/mmintrin.h:typedef int __v2si __attribute__((__vector_size__(8)));
/nix/store/g6dv9av1cswiybklg2plyavqdpf3jgiy-clang-11.0.0/lib/clang/11.0.0/include/mmintrin.h:typedef int __v2si __attribute__((__vector_size__(8)));
/nix/store/az62l4v9m7pqhc5jfh33wsn5fn7jvckl-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/include/mmintrin.h:typedef int __v2si __attribute__ ((__vector_size__ (8)));
/nix/store/v8gdgd5pcxsk6hvx0g22h29py3yxj8hy-clang-11.0.0/lib/clang/11.0.0/include/mmintrin.h:typedef int __v2si __attribute__((__vector_size__(8)));
/nix/store/cy9zzhj8zq4r65qp31hjd4i5c1jn3w66-clang-11.0.0/lib/clang/11.0.0/include/mmintrin.h:typedef int __v2si __attribute__((__vector_size__(8)));
/nix/store/sjfbbay5xhifzpipm4k007svlrpjbx2p-gcc-10.2.0/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include/mmintrin.h:typedef int __v2si __attribute__ ((__vector_size__ (8)));

```

**Comment by spaceotter** [comment]
Well there you go, your wrapper script seems to be providing path hints to clang. I don't think there is much of anything that c2ffi can do about this. You have to create an analogous wrapper for it. c2ffi could allow arbitrary arguments to be forwarded to libclang to facilitate this.

**Comment by attila-lendvai** [comment]
@spaceotter thanks for honing in on the issue!

are you planning to implement something along these lines, and/or recording this as an issue?

**Comment by attila-lendvai** [comment]
FTR, i've tried this on a Debian testing chroot, and sadly, i get the same errors.

i've pushed a file called `./bin/generate-spec-files.sh` into https://github.com/hu-dwim/hu.dwim.sdl that can be used to reproduce the issue.

note re extra clang args: c2ffi seems to print an endless stream of errors, even though it seems to have `-ferror-limit 19`.

**Comment by attila-lendvai** [comment]
FTR, it was due to a c2ffi bug that i have fixed in https://github.com/rpav/c2ffi/pull/96

strictly speaking, it's not ok that these errors are there, but they don't affect the spec generation. i've successfully regenerated the specs for https://github.com/hu-dwim/hu.dwim.sdl/.

**Pull request merged**
