### PR TITLE
Travis support

### PR DESCRIPTION
**Pull request by guicho271828**
Build is successful (see https://travis-ci.org/guicho271828/c2ffi/builds), but this is based on my accout.
Plz set up yours by yourself.

### CODE REVIEW

**Comment by guicho271828** [comment]
BTW it worked both on GCC and CLANG. Also, it would be better if you note that the build requires c++11.

**Comment by skissane** [comment]
While Travis CI was a reasonable option at the time this PR was opened, now GitHub Actions is available and generally speaking better. I have a PR #82 to add GitHub Actions instead. So I suggest closing this PR and going with that one.

**Comment by rpav** [comment]
I am finally getting around to all this.

**Comment by rpav** [comment]
I could have sworn I closed this.  Thanks for the contrib, sorry I didn't get around in time to integrate it!  The Github stuff seems to work now.

**Pull request closed without merging**
