### PR TITLE
added cmake build file that fixes builds on arch

### PR DESCRIPTION
**Pull request by ghost**
There seems to issues with Clang library order and missing LLVM libs when building under Arch. The modified CMakeLists.txt fixes these issues.

### CODE REVIEW

**Comment by rpav** [comment]
Surely this can be folded into the default CMakeLists.txt?

**Comment by ghost** [comment]
I think so. The original CMakelists.txt didn't seem to require "support mcparser option bitreader" llvm libraries, and so I wasn't entirely sure about other build environments. The change in link order of the clang libraries should be okay though. Best to check if it builds on your side and merge the two ?

**Comment by rpav** [comment]
I just tried and it seems to work... not sure why it wouldn't though, I believe it only adds libs to the linker.  I wonder if this fixes it in Ubuntu, but I thought I added all the options there to no avail.

**Comment by ghost** [comment]
Yes, but I figured the disparate libs may not exist. I've replaced the original CMakeLists.txt now.

**Comment by rpav** [comment]
Thanks!

**Pull request merged**
