### PR TITLE
some changes/fixes that i needed to make it build on NixOS 21.05

### PR DESCRIPTION
**Pull request by attila-lendvai**
let me know if i should split this into multiple parts, or if i should change anything.

i'm no expert of cmake, i just struggled through the obstacles.

### CODE REVIEW

**Comment by attila-lendvai** [comment]
@rpav i would appreciate if you could take a look at it at your earliest convenience, because the nix c2ffi PR depends on it (https://github.com/NixOS/nixpkgs/pull/119564).

**Comment by rpav** [comment]
Sorry I'll try and look at this today.

**Comment by attila-lendvai** [comment]
> Sorry I'll try and look at this today.

much appreciated! but don't break your neck over it.

**Comment by rpav** [comment]
Do we really need the change in CMakeLists.txt if the package file does this anyway?  This doesn't seem to be an issue on other platforms and while it's not an issue in this particular version, I'm not sure depending on RTTI being disabled in the long term is a good idea.  (Some recent C++ features use rtti indirectly as I recall.)

**Comment by attila-lendvai** [comment]
the reason i moved it there is what i have found in the comment: LLVM releases are compiled without RTTI. IOW, one cannot be sure whether RTTI is compiled into the LLVM binaries he is linking to.

i'm not well versed in C++ at all, especially in the latest developments, so, if you think it's a bad idea, then i can move it back into the nix file.

**Comment by attila-lendvai** [comment]
@rpav any opinion on this? i'm willing to update it to whichever solution you think is better.

**Comment by rpav** [comment]
Crap sorry fell off my radar again .. let's do this in the package file for now, I'll try and take a look at the necessity for everything else.

**Comment by attila-lendvai** [comment]
@rpav ok, i removed the commit that moved the rtti stuff from the nix file into the cmake file.

please note that Arch latest has moved on to llvm v12, and it breaks the CI. i don't know how to fix it, i don't know how to force arch to install llvm v11.

**Comment by rpav** [comment]
Sorry I'll merge this soon.

**Comment by rpav** [comment]
Sorry for the delay; should be looking at clang-12 shortly too.

**Pull request merged**
